### ISSUE TITLE
Check container status before restart_container

### ISSUE THREAD

**Issue by hjaske** [willfarrell/docker-autoheal#53]
docker inspect [ID] |jq '[.[].State] | [.[].Status,.[].Health.Status]'
[
  "restarting",
  "unhealthy"
]

Container health status can be unhealthy while status is all ready restarting.

Check container status before issuing restart and skip for containers all ready in restarting state?

**Comment by ranezu** [comment]
This would be a great improvement. Our containers sometimes take several minutes to start, and if autoheal is active, it unnecessarily restarts the container. And the worst case scenario is a reboot-loop where the container never actually starts because autoheal keeps restarting it over and over again.

We can circumvent this problem by tweaking the "start-period" parameter of the healthcheck, but IMHO this feature should be implemented in autoheal, too.

**Comment by hasnat** [comment]
I think docker defaults to "stop,start" when requesting a restart on restarting container.
This likely should be addressed in autoheal.
