### ISSUE TITLE
Add sendmail feature

### ISSUE THREAD

**Issue by tkrisztian95** [willfarrell/docker-autoheal#65]
Hi,

First of all: thanks for this great little helper.

I forked the repo for personal use a while ago and added a little extra feature to get email notifications about when autoheal restart containers for me. I'm not using it anymore but I would be glad to contribute it back and create a PR containing the changes.

What do you think, would it make sense to add configurable sendmail or slack message notifications?

Thanks!

**Comment by pschmitt** [comment]
I don't know what exactly what you had in mind regarding the actual implementation. To me the best way to add event notifications would be via a simple event system that interfaces with an external service such as [apprise](https://github.com/caronc/apprise) or [shouter](http://github.com/containrrr/shoutrrr). Otherwise we'll end up re-inventing the wheel here.

**Comment by hasnat** [comment]
This is slightly off autoheal's offerings. Tho I understand the use case.
If you're after docker events, I keep them separate using https://github.com/hasnat/docker-events-notifier
